version: '2'

services:
  "webapp-antisocial":
    container_name: webapp-antisocial
    image: webapp-antisocial
    restart: always
    build:
      context: ../
      dockerfile: docker-assets/Dockerfile-webapp
    ports:
      - "3000:3000"
    volumes:
      - /data/images:/var/app/current/client/uploads
    networks:
      - frontend

  "nginx-antisocial":
    container_name: nginx-antisocial
    image: nginx-antisocial
    restart: always
    build:
      context: ../
      dockerfile: docker-assets/Dockerfile-nginx
    ports:
      - "80:8080"
    networks:
      - frontend

networks:
  frontend:
