branch-defaults:
  master:
    environment: devel-antisocial
global:
  application_name: digitopia-social
  branch: null
  default_platform: Multi-container Docker 17.03.2-ce (Generic)
  default_region: us-east-1
  instance_profile: null
  platform_name: null
  platform_version: null
  repository: null
  sc: git
  workspace_type: Application
